# Deploy - Markov Chain

In [1]:
import numpy as np
import pandas as pd
import deploy_functions as dpf
import hmm
from markovchain import MarkovChain
import helper_functions as hf

import warnings
warnings.filterwarnings('ignore')

### Load Data

In [2]:
cow_1 = pd.read_json('input/cowrie.json.2017_7_4', lines=True)
cow_2 = pd.read_json('input/cowrie.json.2017_7_6', lines=True)
cow_3 = pd.read_json('input/cowrie.json.2017_7_7', lines=True)
cow = pd.concat([cow_1, cow_2, cow_3],axis=0)
cow.head()

,compCS,data,dst_ip,dst_port,duration,encCS,eventid,height,input,isError,...,size,src_ip,src_port,system,timestamp,ttylog,url,username,version,width
0,NaN,NaN,10.10.0.13,2222.0,NaN,NaN,cowrie.session.connect,NaN,NaN,0.0,...,NaN,116.31.116.16,39547.0,cowrie.ssh.factory.CowrieSSHFactory,2017-07-03 18:30:07.569246,NaN,NaN,NaN,NaN,NaN
1,[none],NaN,NaN,NaN,NaN,"[aes128-ctr, aes192-ctr, aes256-ctr, aes256-cb...",cowrie.client.version,NaN,NaN,0.0,...,NaN,116.31.116.16,NaN,"HoneyPotSSHTransport,523,116.31.116.16",2017-07-03 18:30:08.235671,NaN,NaN,NaN,SSH-2.0-PUTTY,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,cowrie.login.success,NaN,NaN,0.0,...,NaN,116.31.116.16,NaN,SSHService 'ssh-userauth' on HoneyPotSSHTransp...,2017-07-03 18:30:10.585142,NaN,NaN,root,NaN,NaN
3,NaN,NaN,NaN,NaN,9.96463,NaN,cowrie.session.closed,NaN,NaN,0.0,...,NaN,116.31.116.16,NaN,"HoneyPotSSHTransport,523,116.31.116.16",2017-07-03 18:30:17.902600,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,10.10.0.13,2222.0,NaN,NaN,cowrie.session.connect,NaN,NaN,0.0,...,NaN,116.31.116.16,22040.0,cowrie.ssh.factory.CowrieSSHFactory,2017-07-03 18:30:44.657703,NaN,NaN,NaN,NaN,NaN

### Process Data

In [3]:
seq = dpf.proc_data(cow)

HBox(children=(IntProgress(value=0, max=22449), HTML(value='')))

In [4]:
print ('Some attack sequences...')
seq[1], seq[10], seq[20]

Some attack sequences...

([16,
  14,
  12,
  5,
  8,
  5,
  2,
  5,
  8,
  5,
  8,
  5,
  8,
  8,
  8,
  5,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  8,
  8,
  8,
  5,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  3,
  8,
  8,
  8,
  4,
  8,
  7,
  8,
  8,
  8,
  8,
  8,
  8,
  5,
  8,
  8,
  5,
  8,
  11,
  15],
 [16, 14, 12, 5, 11, 15],
 [16, 15])

### Train Markov Chain

In [7]:
mod = MarkovChain(states=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
mod.train(seq)

### Prediction

In [8]:
true = 0
tot = 0
d = seq[9670]

pred = []
pred.append(16)

for i in range(1, len(d)):
    s = d[:i]
    nxt = dpf.mc_predict_next_state(mod, s)
    if nxt == d[i]:
        true += 1
    tot += 1
    pred.append(nxt)    
    
print (true/tot)

0.8

In [9]:
print ('Max probablity sequence: \n')
mod.most_probable_sequence(start=16, length=7)

Max probablity sequence:

[16, 14, 12, 5, 8, 8, 8]

In [10]:
t = pd.DataFrame(mod.transition)
t

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008696,0.991304,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.055310,0.772966,0.171724,0.0,0.000000,0.000000
2,0.000000,0.000000,0.098055,0.000058,0.000288,0.891127,0.000000,0.001554,0.003798,0.000000,0.000000,0.004431,0.000058,0.000000,0.000000,0.000000,0.0,0.000633,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
5,0.000000,0.000000,0.230996,0.009018,0.000570,0.016817,0.000000,0.000902,0.736161,0.000000,0.000000,0.004651,0.000000,0.000000,0.000000,0.000886,0.0,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
7,0.000000,0.000000,0.005468,0.000000,0.000000,0.000000,0.000000,0.000000,0.994532,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
8,0.000007,0.000000,0.001463,0.174468,0.020936,0.053787,0.000000,0.006771,0.731854,0.000000,0.000000,0.010550,0.000011,0.000000,0.000000,0.000001,0.0,0.000109,0.000042
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.337931,0.605687,0.000000,0.000000,0.000000,0.000000,0.056382,0.0,0.000000,0.000000
10,0.003082,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.292645,0.690190,0.000000,0.000585,0.000000,0.000000,0.013498,0.0,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001258,0.006816,0.000000,0.000000,0.991926,0.0,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.001143,0.000000,0.844380,0.000623,0.000312,0.000000,0.000000,0.000000,0.153542,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.459918,0.023406,0.516676,0.0,0.000000,0.000000
14,0.003462,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077630,0.000000,0.627896,0.000000,0.000000,0.291012,0.0,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
16,0.000000,0.324503,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.023319,0.419522,0.232656,0.0,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.538462,0.000000,0.000000,0.000000,0.032051,0.0,0.429487,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141509,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.858491

In [13]:
print (d[27:40])

[8, 8, 11, 15]

In [14]:
print (pred[27:40])

[8, 8, 8, 15]